/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void mainScreenClicked(GButton source, GEvent event) { //_CODE_:mainScreen:980433:
  screen = "main"; 
  h_start = hour();
  m_start = minute();
  s_start = second();
} //_CODE_:mainScreen:980433:

public void playMusicPressed(GButton source, GEvent event) { //_CODE_:playMusic:530303:
  if(musicPaused == false) {
    
    if(chosenSong == "classical")
      classical.play(); 
    else if(chosenSong == "brownNoise")
      brownNoise.play(); 
    else
      lofi.play(); 
    
    playMusic.setText("Pause Music"); 
    musicPaused = true; 
  }
  
  else {
    
    if(chosenSong == "classical")
      classical.pause(); 
    else if(chosenSong == "brownNoise")
      brownNoise.pause(); 
    else
      lofi.pause(); 
    
    playMusic.setText("Play Music"); 
    musicPaused = false; 
    
  }
    
} //_CODE_:playMusic:530303:

public void taskOneButPressed(GButton source, GEvent event) { //_CODE_:taskOneBut:975853:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:taskOneBut:975853:

public void taskTwoButPressed(GButton source, GEvent event) { //_CODE_:taskTwoBut:708862:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:taskTwoBut:708862:

public void taskThreeButPressed(GButton source, GEvent event) { //_CODE_:taskThreeBut:814104:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:taskThreeBut:814104:

public void addTaskButPressed(GButton source, GEvent event) { //_CODE_:addTaskBut:636625:
  println("addTaskBut - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:addTaskBut:636625:

public void stopwatchBtn_click(GButton source, GEvent event) { //_CODE_:stopwatchBtn:937837:
  println("stopwatchBtn - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:stopwatchBtn:937837:

public void taskOneTyped(GTextArea source, GEvent event) { //_CODE_:taskOne:271505:
  println("taskOne - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:taskOne:271505:

public void taskTwoTyped(GTextArea source, GEvent event) { //_CODE_:taskTwo:474154:
  println("taskTwo - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:taskTwo:474154:

public void taskThreeTyped(GTextArea source, GEvent event) { //_CODE_:taskThree:503171:
  println("textarea3 - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:taskThree:503171:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  mainScreen = new GButton(this, 365, 704, 80, 30);
  mainScreen.setText("Main Screen");
  mainScreen.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  mainScreen.addEventHandler(this, "mainScreenClicked");
  playMusic = new GButton(this, 669, 14, 80, 30);
  playMusic.setText("Play Music");
  playMusic.addEventHandler(this, "playMusicPressed");
  taskOneBut = new GButton(this, 91, 306, 38, 32);
  taskOneBut.setText("Done");
  taskOneBut.addEventHandler(this, "taskOneButPressed");
  taskTwoBut = new GButton(this, 90, 392, 41, 30);
  taskTwoBut.setText("Done");
  taskTwoBut.addEventHandler(this, "taskTwoButPressed");
  taskThreeBut = new GButton(this, 89, 477, 42, 30);
  taskThreeBut.setText("Done");
  taskThreeBut.addEventHandler(this, "taskThreeButPressed");
  addTaskBut = new GButton(this, 335, 261, 80, 30);
  addTaskBut.setText("Add Task");
  addTaskBut.addEventHandler(this, "addTaskButPressed");
  taskListLabel = new GLabel(this, 100, 250, 206, 44);
  taskListLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  taskListLabel.setText("Task List");
  taskListLabel.setOpaque(false);
  stopwatchBtn = new GButton(this, 500, 194, 80, 30);
  stopwatchBtn.setText("Start");
  stopwatchBtn.addEventHandler(this, "stopwatchBtn_click");
  taskOne = new GTextArea(this, 146, 306, 120, 51, G4P.SCROLLBARS_VERTICAL_ONLY);
  taskOne.setOpaque(true);
  taskOne.addEventHandler(this, "taskOneTyped");
  taskTwo = new GTextArea(this, 147, 388, 120, 48, G4P.SCROLLBARS_VERTICAL_ONLY);
  taskTwo.setOpaque(true);
  taskTwo.addEventHandler(this, "taskTwoTyped");
  taskThree = new GTextArea(this, 144, 474, 120, 44, G4P.SCROLLBARS_VERTICAL_ONLY);
  taskThree.setOpaque(true);
  taskThree.addEventHandler(this, "taskThreeTyped");
}

// Variable declarations 
// autogenerated do not edit
GButton mainScreen; 
GButton playMusic; 
GButton taskOneBut; 
GButton taskTwoBut; 
GButton taskThreeBut; 
GButton addTaskBut; 
GLabel taskListLabel; 
GButton stopwatchBtn; 
GTextArea taskOne; 
GTextArea taskTwo; 
GTextArea taskThree; 
