 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void mainScreenClicked(GButton source, GEvent event) { //_CODE_:mainScreen:980433:
  screen = "main"; 
  h_start = hour();
  m_start = minute();
  s_start = second();
} //_CODE_:mainScreen:980433:

public void playMusicPressed(GButton source, GEvent event) { //_CODE_:playMusic:530303:
  if(musicPaused == false) {
    
    if(chosenSong == "classical")
      classical.play(); 
    else if(chosenSong == "brownNoise")
      brownNoise.play(); 
    else
      lofi.play(); 
    
    playMusic.setText("Pause Music"); 
    musicPaused = true; 
  }
  
  else {
    
    if(chosenSong == "classical")
      classical.pause(); 
    else if(chosenSong == "brownNoise")
      brownNoise.pause(); 
    else
      lofi.pause(); 
    
    playMusic.setText("Play Music"); 
    musicPaused = false; 
    
  }
    
} //_CODE_:playMusic:530303:

public void stopwatchBtn_click(GButton source, GEvent event) { //_CODE_:stopwatchBtn:876681:
  if (start) {
    h_start = hour();
    m_start = minute();
    s_start = second();
    
    start = false;
  }
  
  if (pause) {
    pause = false;
    stopwatchBtn.setText("Resume");
    
    h_pause = hour();
    m_pause = minute();
    s_pause = second();
    
    noLoop();
  }
  else { 
    pause = true;
    stopwatchBtn.setText("Pause");
    
    h_current = hour();
    m_current = minute();
    s_current = second();
    
    hPaused = h_current - h_pause;
    mPaused = m_current - m_pause;
    if (mPaused < 0) {
      hPaused -= 1;
      mPaused += 60;
    }
    sPaused = s_current - s_pause;
    if (sPaused < 0) {
      mPaused -= 1;
      sPaused += 60;
    }    
    
    loop();
  }
} //_CODE_:stopwatchBtn:876681:




// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  mainScreen = new GButton(this, 381, 563, 80, 30);
  mainScreen.setText("Main Screen");
  mainScreen.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  mainScreen.addEventHandler(this, "mainScreenClicked");
  playMusic = new GButton(this, 691, 14, 80, 30);
  playMusic.setText("Play Music");
  playMusic.addEventHandler(this, "playMusicPressed");
  stopwatchBtn = new GButton(this, 400, 180, 80, 30);
  stopwatchBtn.setText("Start");
  stopwatchBtn.addEventHandler(this, "stopwatchBtn_click");
}

// Variable declarations 
// autogenerated do not edit
GButton mainScreen; 
GButton playMusic; 
GButton stopwatchBtn; 